_name_: deepsea
dataset_name: null
dest_path: /mnt/nas/share2/home/by/hyena-dna/data/DeepSea/deepsea_train/
# datasets are: train.csv.gz test.csv.gz val.csv.gz
max_length: 1024
d_output: 919 # binary classification task
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: 4400000
__l_max: ${.max_length}
shuffle: true  # set this as default!
tokenizer_name: char
cache_dir: null
batch_size_eval: ${eval:${.batch_size} * 2}
pin_memory: True
rc_aug: False
metric: roc
# https://www.nature.com/articles/nmeth.3547#Sec2
# orignal train code at DeepSea/deepsea_train/4_train.lua
#For evaluating performance on the test set, we used area under the receiver operating characteristic curve (AUC).