_name_: deepstarr
dataset_name: null
dest_path: /mnt/nas/share2/home/by/hyena-dna/data/DeepSTARR
max_length: 248
d_output: 2 # actually it's regression task
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: 402296
__l_max: ${.max_length}
shuffle: true  # set this as default!
tokenizer_name: char
cache_dir: null
batch_size_eval: ${eval:${.batch_size} * 2}
pin_memory: True
rc_aug: False
metric: 
  - pearsonr_mean
  - pearsonr_dev
  - pearsonr_hk