_name_: gue  # this links to the overall SequenceDataset of all nucleotide transformer datasets
dataset_name: enhancer  # this specifies which dataset in nuc trx
dest_path: null  # path to overall nuc trx datasets
max_length: ${.${.dataset_name}.max_length}
d_output: ${.${.dataset_name}.classes} 
use_padding: True
padding_side: left
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
metric: ${.${.dataset_name}.metric}
# these are used to find the right attributes automatically for each dataset
virus/covid:
  train_len: 77669
  classes: 9
  max_length: 1000
  metric: f1_macro #the paper only says "f1"
EMP/H3:
  train_len: 11971
  classes: 2
  max_length: 500
  metric: mcc



