wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.3
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1721458931
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 3
      - 23
      4: 3.8.19
      5: 0.17.3
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
